name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub  #here telling that login first to docker hub and push theer the image in docker hub from fithub workflow
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} #here getting the dickerhub user name which is we saved in action and secret inn github
        password: ${{ secrets.DOCKER_PASSWORD }} #same here

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile.user #which docker that path must be here //like here user docker file 
        push: true
        tags: metavy/cicd-check:latest  # Replace with your Docker Hub username and repository

    - name: Verify Pushed Image
      run: docker pull metavy/cicd-check:latest  # Replace with your Docker Hub username and repository
